const CODE = {
  SUCCESS: 0,
  FAIL: -1,
  ERR_REQUEST_FREQUENTLY: 100,
  ERR_IDENTIFY_EXPIRE: 101,
  ERR_IDENTIFY_INVALID: 102,
  ERR_IDENTIFY_EMPTY: 103,
  ERR_USER_REGISTERED: 104,
  ERR_USER_REGISTER_FAIL: 105
}

const MSG = {
  SUCCESS: '成功',
  FAIL: '失败',
  ERR_REQUEST_FREQUENTLY: '请求频繁',
  ERR_IDENTIFY_EXPIRE: '验证码已过期',
  ERR_IDENTIFY_INVALID: '验证码无效',
  ERR_IDENTIFY_EMPTY: '验证码为空',
  ERR_USER_REGISTERED: '用户名已注册',
  ERR_USER_REGISTER_FAIL: '用户名注册失败'
}

export {
  CODE,
  MSG
}
